namespace Byzantium1071.Campaign.Settings
{
    public interface IB1071Settings
    {
        int SettingsProfileVersion { get; set; }
        int TownPoolMax { get; set; }
        int CastlePoolMax { get; set; }
        int OtherPoolMax { get; set; }
        bool UseTinyPoolsForTesting { get; set; }
        int TinyPoolDivisor { get; set; }
        int TinyPoolMinimum { get; set; }
        float ProsperityNormalizer { get; set; }
        float MaxPoolProsperityMinScale { get; set; }
        float MaxPoolProsperityMaxScale { get; set; }
        float SecurityBonusMinScale { get; set; }
        float SecurityBonusMaxScale { get; set; }
        float MaxPoolHearthMultiplier { get; set; }
        float TownRegenMinPercent { get; set; }
        float TownRegenMaxPercent { get; set; }
        float CastleRegenMinPercent { get; set; }
        float CastleRegenMaxPercent { get; set; }
        float OtherRegenPercent { get; set; }
        int HearthNormalizer { get; set; }
        float HearthBonusMaxPercent { get; set; }
        float SiegeRegenMultiplierPercent { get; set; }
        int MinimumDailyRegen { get; set; }
        int CastleMinimumDailyRegen { get; set; }
        bool EnableCastleSupplyChain { get; set; }
        int CastleVillageLevyPercent { get; set; }
        int CastleCutOffDailyRegen { get; set; }
        bool EnableDepletedEmergencyRegen { get; set; }
        int DepletedRegenThresholdPercent { get; set; }
        int DepletedRegenBonusAtZero { get; set; }
        float RegenCapPercent { get; set; }
        bool EnableRegenSoftCap { get; set; }
        float RegenSoftCapStartRatio { get; set; }
        float RegenSoftCapStrength { get; set; }
        float RegenStressFloorPercent { get; set; }
        float SecurityRegenMinScale { get; set; }
        float SecurityRegenMaxScale { get; set; }
        float FoodRegenMinScale { get; set; }
        float FoodRegenMaxScale { get; set; }
        float FoodStocksNormalizer { get; set; }
        float LoyaltyRegenMinScale { get; set; }
        float LoyaltyRegenMaxScale { get; set; }
        int BaseManpowerCostPerTroop { get; set; }
        int VillageVolunteerTierMax { get; set; }
        int TownVolunteerTierMax { get; set; }
        int TiersPerExtraCost { get; set; }
        int CostMultiplierPercent { get; set; }
        bool EnableTierSurvivability { get; set; }
        bool EnableTierArmorSimulation { get; set; }
        int EliteSurvivabilityPreset { get; set; }
        int HireUpgradeCostPreset { get; set; }
        int WagePreset { get; set; }
        bool EnableGarrisonWageDiscount { get; set; }
        int GarrisonWagePercent { get; set; }
        bool BlockEnemyRealmRecruitment { get; set; }
        int ForeignRecruitCostPreset { get; set; }
        bool EnableVerboseModLog { get; set; }
        bool ShowPlayerDebugMessages { get; set; }
        bool UseOnUnitRecruitedFallbackForPlayer { get; set; }
        bool LogAiManpowerConsumption { get; set; }
        bool TelemetryDebugLogs { get; set; }
        bool ShowTelemetryInOverlay { get; set; }
        bool EnableOverlay { get; set; }
        bool EnableOverlayHotkey { get; set; }
        int OverlayHotkeyChoice { get; set; }
        bool OverlayShowSettlementName { get; set; }
        bool OverlayShowPoolName { get; set; }
        int OverlayLedgerDefaultTab { get; set; }
        int OverlayLedgerRowsPerPage { get; set; }
        int OverlayPanelTopOffset { get; set; }
        int OverlayPanelLeftOffset { get; set; }
        bool EnableWarEffects { get; set; }
        int RaidManpowerDrainPercent { get; set; }
        int RaidDailyPoolDrainCapPercent { get; set; }
        int SiegeDevastateRetainPercent { get; set; }
        int SiegePillageRetainPercent { get; set; }
        int SiegeMercyRetainPercent { get; set; }
        float BattleCasualtyDrainMultiplier { get; set; }
        int ConquestPoolRetainPercent { get; set; }
        bool EnableDynamicConquestProtection { get; set; }
        int ConquestDepletedRetainPercent { get; set; }
        int ConquestDepletedThresholdPercent { get; set; }
        bool EnableDelayedRecovery { get; set; }
        int RaidRecoveryDays { get; set; }
        int SiegeRecoveryDays { get; set; }
        int ConquestRecoveryDays { get; set; }
        int RecoveryPenaltyRaidPercent { get; set; }
        int RecoveryPenaltySiegePercent { get; set; }
        int RecoveryPenaltyConquestPercent { get; set; }
        int RecoveryPenaltyMaxPercent { get; set; }
        bool ReduceRecoveryPenaltyWhenDepleted { get; set; }
        int RecoveryDepletedThresholdPercent { get; set; }
        bool EnableRecruitmentVariance { get; set; }
        int VolunteerVariancePercent { get; set; }
        int RecoveryVariancePercent { get; set; }
        bool EnableSeasonalRegen { get; set; }
        int SpringSummerRegenMultiplier { get; set; }
        int WinterRegenMultiplier { get; set; }
        bool EnablePeaceDividend { get; set; }
        int PeaceDividendMultiplier { get; set; }
        bool EnableCultureDiscount { get; set; }
        int CultureCostPercent { get; set; }
        bool EnableGovernorBonus { get; set; }
        float GovernorStewardRegenDivisor { get; set; }
        float GovernorLeadershipPoolDivisor { get; set; }
        bool EnableManpowerAlerts { get; set; }
        int AlertThresholdPercent { get; set; }
        bool EnableMilitiaLink { get; set; }
        int MilitiaManpowerMinScale { get; set; }
        int MilitiaManpowerMaxScale { get; set; }
        bool EnableWarExhaustion { get; set; }
        float ExhaustionDailyDecay { get; set; }
        float ExhaustionRegenDivisor { get; set; }
        float ExhaustionMaxScore { get; set; }
        float BattleExhaustionPerCasualty { get; set; }
        float RaidExhaustionGain { get; set; }
        float SiegeExhaustionDefender { get; set; }
        float SiegeExhaustionAttacker { get; set; }
        float ConquestExhaustionGain { get; set; }
        bool EnableNobleCaptureExhaustion { get; set; }
        float NobleCaptureExhaustionGain { get; set; }
        bool EnableTierWeightedCasualties { get; set; }
        bool EnableManpowerDepletionAmplifier { get; set; }
        float ManpowerDepletionAmplifier { get; set; }
        bool EnableExhaustionDiplomacyPressure { get; set; }
        float DiplomacyNoNewWarThreshold { get; set; }
        float DiplomacyPeacePressureThreshold { get; set; }
        float DiplomacyWarSupportPenaltyPerPoint { get; set; }
        float DiplomacyPeaceSupportBonusPerPoint { get; set; }
        bool EnableForcedPeaceAtCrisis { get; set; }
        float DiplomacyForcedPeaceThreshold { get; set; }
        int DiplomacyForcedPeaceCooldownDays { get; set; }
        int DiplomacyForcedPeaceMaxActiveWars { get; set; }
        int MinWarDurationDaysBeforeForcedPeace { get; set; }
        float EarlyWarPeacePenaltyStrength { get; set; }
        bool IgnoreForcedPeaceIfEnemyBesiegingCoreSettlement { get; set; }
        bool EnableTruceEnforcement { get; set; }
        int ForcedPeaceTruceDays { get; set; }
        int DiplomacyMajorWarPressureStartCount { get; set; }
        float DiplomacyExtraPeaceBiasPerMajorWar { get; set; }
        float DiplomacyForcedPeaceThresholdReductionPerMajorWar { get; set; }
        bool EnableMultiFrontWarRelief { get; set; }
        int EmergencyMinWarDays { get; set; }
        int EmergencyManpowerThresholdPercent { get; set; }
        int EmergencyWarCountThreshold { get; set; }
        bool DiplomacyEnforcePlayerParity { get; set; }
        bool EnableDiplomacyPressureBands { get; set; }
        float PressureBandRisingStart { get; set; }
        float PressureBandCrisisStart { get; set; }
        float PressureBandHysteresis { get; set; }
        float PeaceBiasBandLow { get; set; }
        float PeaceBiasBandHigh { get; set; }
        float WarSupportPenaltyCap { get; set; }
        float PeaceSupportBonusCap { get; set; }
        bool EnableManpowerDiplomacyPressure { get; set; }
        int ManpowerDiplomacyThresholdPercent { get; set; }
        float ManpowerDiplomacyPressureStrength { get; set; }
        bool DiplomacyDebugLogs { get; set; }
        bool EnableSettlementManpowerTooltips { get; set; }
        bool EnableSlaveEconomy { get; set; }
        int SlaveHearthDivisor { get; set; }
        float SlaveRansomMultiplier { get; set; }
        float SlaveManpowerPerUnit { get; set; }
        int SlaveManpowerCapPerTown { get; set; }
        float SlaveProsperityPerUnit { get; set; }
        float SlaveConstructionAcceleration { get; set; }
        float SlaveConstructionBonusCap { get; set; }
        float SlaveFoodConsumptionPerUnit { get; set; }
        float SlaveDailyDecayPercent { get; set; }
        float SlaveCapPerProsperity { get; set; }
        int SlaveCapMinimum { get; set; }
        float SlavePriceDecayRate { get; set; }
        bool EnableSlaveConversionSelection { get; set; }
        bool EnableEnslavementRogueryXp { get; set; }
        float EnslavementRogueryXpMultiplier { get; set; }
        bool EnableDemobilizationSystem { get; set; }
        int DemobilizationIntensityPreset { get; set; }
        bool EnableDemobilizationHotkey { get; set; }
        int DemobilizationHotkeyChoice { get; set; }
        int DemobilizationWarningLeadDays { get; set; }
        bool DemobilizationWarningPopup { get; set; }
        bool DemobilizationNotifyPlayer { get; set; }
        int DemobilizationExtensionDays { get; set; }
        int DemobilizationExtensionGoldPerTierDay { get; set; }
        bool DemobilizationAiExtensionsEnabled { get; set; }
        int DemobilizationAiExtensionGoldBufferMultiplier { get; set; }
        int DemobilizationPromotionBonusDays { get; set; }
        int DemobilizationDailyCapPercent { get; set; }
        int DemobilizationMaxDailyDepartures { get; set; }
        bool EnableDemobilizationSeasonality { get; set; }
        int DemobilizationSpringSummerThresholdPercent { get; set; }
        int DemobilizationWinterThresholdPercent { get; set; }
        bool EnableDemobilizationCrisisCompression { get; set; }
        int DemobilizationCrisisThresholdPercent { get; set; }
        int DemobilizationMaxExtensions { get; set; }
        int DemobilizationNotifyIntervalDays { get; set; }
        bool EnableDemobilizationVeteranReturn { get; set; }
        int DemobilizationManpowerReturnPercent { get; set; }
        int DemobilizationVeteranRetentionDays { get; set; }
        int DemobilizationVeteranSettlingDays { get; set; }
        int DemobilizationVeteranScatterPercent { get; set; }
        int DemobilizationRecallGoldPerTier { get; set; }
        int DemobilizationVeteranRecallAccess { get; set; }
        bool EnableDemobilizationRemoteRecall { get; set; }
        bool EnableVeteranRecallHotkey { get; set; }
        int VeteranRecallHotkeyChoice { get; set; }
        int DemobilizationCourierSpeed { get; set; }
        int DemobilizationMarchSpeed { get; set; }
        bool EnableDemobilizationAiRecall { get; set; }
        int DemobilizationT1ServiceDays { get; set; }
        int DemobilizationT2ServiceDays { get; set; }
        int DemobilizationT3ServiceDays { get; set; }
        int DemobilizationT4ServiceDays { get; set; }
        int DemobilizationT5ServiceDays { get; set; }
        int DemobilizationT6ServiceDays { get; set; }
        int SlaveConstructionBonusDays { get; set; }
        bool EnableExperimentalHoverFallback { get; set; }
        int TooltipRefreshMs { get; set; }
        bool EnableMinorFactionIncome { get; set; }
        int MinorFactionMercenaryStipendPerTier { get; set; }
        int MinorFactionUnalignedStipendPerTier { get; set; }
        bool EnableGovernanceStrain { get; set; }
        float GovernanceStrainDecayPerDay { get; set; }
        float GovernanceMaxLoyaltyPenalty { get; set; }
        float GovernanceMaxSecurityPenalty { get; set; }
        float GovernanceMaxProsperityPenalty { get; set; }
        float GovernanceStrainCap { get; set; }
        float MaxCombinedModProsperityPenalty { get; set; }
        bool EnableGovernanceStabilization { get; set; }
        bool GovernanceStabilizationNotifyPlayer { get; set; }
        bool GovernanceStabilizationAiEnabled { get; set; }
        float GovernanceStabilizationAiStrainThreshold { get; set; }
        int GovernanceStabilizationAiGoldMultiplier { get; set; }
        int GovernanceStabilizationAiHeroCooldownDays { get; set; }
        int GovernanceStabilizationCostDonative { get; set; }
        int GovernanceStabilizationDurationDonative { get; set; }
        float GovernanceStabilizationStrainDonative { get; set; }
        float GovernanceStabilizationLoyaltyDonative { get; set; }
        float GovernanceStabilizationSecurityDonative { get; set; }
        float GovernanceStabilizationDecayDonative { get; set; }
        int GovernanceStabilizationCostElites { get; set; }
        int GovernanceStabilizationDurationElites { get; set; }
        float GovernanceStabilizationStrainElites { get; set; }
        float GovernanceStabilizationLoyaltyElites { get; set; }
        float GovernanceStabilizationSecurityElites { get; set; }
        float GovernanceStabilizationDecayElites { get; set; }
        int GovernanceStabilizationCostAmnesty { get; set; }
        int GovernanceStabilizationDurationAmnesty { get; set; }
        float GovernanceStabilizationStrainAmnesty { get; set; }
        float GovernanceStabilizationLoyaltyAmnesty { get; set; }
        float GovernanceStabilizationSecurityAmnesty { get; set; }
        float GovernanceStabilizationDecayAmnesty { get; set; }
        bool EnableFrontierDevastation { get; set; }
        float DevastationPerRaid { get; set; }
        float DevastationDecayPerDay { get; set; }
        float DevastationMaxHearthPenalty { get; set; }
        float DevastationMaxProsperityPenalty { get; set; }
        float DevastationMaxSecurityPenalty { get; set; }
        float DevastationMaxFoodPenaltyPerVillage { get; set; }
        bool EnableCastleRecruitment { get; set; }
        int CastlePrisonerAutoEnslaveTierMax { get; set; }
        int CastleRecruitT4Days { get; set; }
        int CastleRecruitT5Days { get; set; }
        int CastleRecruitT6Days { get; set; }
        int CastleRecruitGoldT2 { get; set; }
        int CastleRecruitGoldT3 { get; set; }
        int CastleRecruitGoldT4 { get; set; }
        int CastleRecruitGoldT5 { get; set; }
        int CastleRecruitGoldT6 { get; set; }
        bool CastleRecruitDrainsManpower { get; set; }
        int CastleElitePoolMax { get; set; }
        int CastleEliteRegenMin { get; set; }
        int CastleEliteRegenMax { get; set; }
        int CastleEliteManpowerCost { get; set; }
        bool CastleEliteAiRecruits { get; set; }
        int CastleHoldingFeePercent { get; set; }
        bool CastleOpenAccess { get; set; }
        int CastleRecruitmentAccess { get; set; }
        bool EnableDiversifiedCastlePool { get; set; }
        int CastlePoolT2LevyPercent { get; set; }
        int CastlePoolT2NoblePercent { get; set; }
        int CastlePoolT3T4Percent { get; set; }
        int CastlePoolT5PlusPercent { get; set; }
        bool EnableDynamicPoolCapacity { get; set; }
        int CastleElitePoolBaseCapDynamic { get; set; }
        float CastleElitePoolProsperityScaling { get; set; }
        int CastleElitePoolWallBonus { get; set; }
        int CastleAiGoldBufferMultiplier { get; set; }
        bool EnableVillageInvestment { get; set; }
        int VillageInvestCostModest { get; set; }
        int VillageInvestCostGenerous { get; set; }
        int VillageInvestCostGrand { get; set; }
        int VillageInvestDurationModest { get; set; }
        int VillageInvestDurationGenerous { get; set; }
        int VillageInvestDurationGrand { get; set; }
        float VillageInvestHearthModest { get; set; }
        float VillageInvestHearthGenerous { get; set; }
        float VillageInvestHearthGrand { get; set; }
        int VillageInvestRelationModest { get; set; }
        int VillageInvestRelationGenerous { get; set; }
        int VillageInvestRelationGrand { get; set; }
        float VillageInvestInfluenceModest { get; set; }
        float VillageInvestInfluenceGenerous { get; set; }
        float VillageInvestInfluenceGrand { get; set; }
        int VillageInvestPowerModest { get; set; }
        int VillageInvestPowerGenerous { get; set; }
        int VillageInvestPowerGrand { get; set; }
        int VillageInvestPowerCap { get; set; }
        int VillageInvestCrossClanRelation { get; set; }
        bool VillageInvestAiEnabled { get; set; }
        int VillageInvestAiGoldMultiplier { get; set; }
        int VillageInvestAiChance { get; set; }
        bool VillageInvestAiRandomTier { get; set; }
        int VillageInvestAiHeroCooldownDays { get; set; }
        int VillageInvestAiHearthCeiling { get; set; }
        bool VillageInvestNotifyPlayer { get; set; }
        bool EnableTownInvestment { get; set; }
        int TownInvestCostModest { get; set; }
        int TownInvestCostGenerous { get; set; }
        int TownInvestCostGrand { get; set; }
        int TownInvestDurationModest { get; set; }
        int TownInvestDurationGenerous { get; set; }
        int TownInvestDurationGrand { get; set; }
        float TownInvestProsperityModest { get; set; }
        float TownInvestProsperityGenerous { get; set; }
        float TownInvestProsperityGrand { get; set; }
        int TownInvestRelationModest { get; set; }
        int TownInvestRelationGenerous { get; set; }
        int TownInvestRelationGrand { get; set; }
        float TownInvestInfluenceModest { get; set; }
        float TownInvestInfluenceGenerous { get; set; }
        float TownInvestInfluenceGrand { get; set; }
        int TownInvestPowerModest { get; set; }
        int TownInvestPowerGenerous { get; set; }
        int TownInvestPowerGrand { get; set; }
        int TownInvestPowerCap { get; set; }
        int TownInvestCrossClanRelation { get; set; }
        bool TownInvestAiEnabled { get; set; }
        int TownInvestAiGoldMultiplier { get; set; }
        int TownInvestAiChance { get; set; }
        bool TownInvestAiRandomTier { get; set; }
        int TownInvestAiHeroCooldownDays { get; set; }
        int TownInvestAiProsperityCeiling { get; set; }
        bool TownInvestNotifyPlayer { get; set; }
        bool EnableClanSurvival { get; set; }
        bool RescueRebelClans { get; set; }
        bool PurgeLeftoverRebelClans { get; set; }
        int ClanSurvivalGracePeriodDays { get; set; }
        float ClanSurvivalCultureWeight { get; set; }
    }
}
