using Byzantium1071.Campaign.Settings;

namespace Byzantium1071.Tests
{
    internal sealed class FakeSettings : IB1071Settings
    {
        public int SettingsProfileVersion { get; set; }
        public int TownPoolMax { get; set; }
        public int CastlePoolMax { get; set; }
        public int OtherPoolMax { get; set; }
        public bool UseTinyPoolsForTesting { get; set; }
        public int TinyPoolDivisor { get; set; }
        public int TinyPoolMinimum { get; set; }
        public float ProsperityNormalizer { get; set; }
        public float MaxPoolProsperityMinScale { get; set; }
        public float MaxPoolProsperityMaxScale { get; set; }
        public float SecurityBonusMinScale { get; set; }
        public float SecurityBonusMaxScale { get; set; }
        public float MaxPoolHearthMultiplier { get; set; }
        public float TownRegenMinPercent { get; set; }
        public float TownRegenMaxPercent { get; set; }
        public float CastleRegenMinPercent { get; set; }
        public float CastleRegenMaxPercent { get; set; }
        public float OtherRegenPercent { get; set; }
        public int HearthNormalizer { get; set; }
        public float HearthBonusMaxPercent { get; set; }
        public float SiegeRegenMultiplierPercent { get; set; }
        public int MinimumDailyRegen { get; set; }
        public int CastleMinimumDailyRegen { get; set; }
        public bool EnableCastleSupplyChain { get; set; }
        public int CastleVillageLevyPercent { get; set; }
        public int CastleCutOffDailyRegen { get; set; }
        public bool EnableDepletedEmergencyRegen { get; set; }
        public int DepletedRegenThresholdPercent { get; set; }
        public int DepletedRegenBonusAtZero { get; set; }
        public float RegenCapPercent { get; set; }
        public bool EnableRegenSoftCap { get; set; }
        public float RegenSoftCapStartRatio { get; set; }
        public float RegenSoftCapStrength { get; set; }
        public float RegenStressFloorPercent { get; set; }
        public float SecurityRegenMinScale { get; set; }
        public float SecurityRegenMaxScale { get; set; }
        public float FoodRegenMinScale { get; set; }
        public float FoodRegenMaxScale { get; set; }
        public float FoodStocksNormalizer { get; set; }
        public float LoyaltyRegenMinScale { get; set; }
        public float LoyaltyRegenMaxScale { get; set; }
        public int BaseManpowerCostPerTroop { get; set; }
        public int VillageVolunteerTierMax { get; set; }
        public int TownVolunteerTierMax { get; set; }
        public int TiersPerExtraCost { get; set; }
        public int CostMultiplierPercent { get; set; }
        public bool EnableTierSurvivability { get; set; }
        public bool EnableTierArmorSimulation { get; set; }
        public int EliteSurvivabilityPreset { get; set; }
        public int HireUpgradeCostPreset { get; set; }
        public int WagePreset { get; set; }
        public bool EnableGarrisonWageDiscount { get; set; }
        public int GarrisonWagePercent { get; set; }
        public bool BlockEnemyRealmRecruitment { get; set; }
        public int ForeignRecruitCostPreset { get; set; }
        public bool EnableVerboseModLog { get; set; }
        public bool ShowPlayerDebugMessages { get; set; }
        public bool UseOnUnitRecruitedFallbackForPlayer { get; set; }
        public bool LogAiManpowerConsumption { get; set; }
        public bool TelemetryDebugLogs { get; set; }
        public bool ShowTelemetryInOverlay { get; set; }
        public bool EnableOverlay { get; set; }
        public bool EnableOverlayHotkey { get; set; }
        public int OverlayHotkeyChoice { get; set; }
        public bool OverlayShowSettlementName { get; set; }
        public bool OverlayShowPoolName { get; set; }
        public int OverlayLedgerDefaultTab { get; set; }
        public int OverlayLedgerRowsPerPage { get; set; }
        public int OverlayPanelTopOffset { get; set; }
        public int OverlayPanelLeftOffset { get; set; }
        public bool EnableWarEffects { get; set; }
        public int RaidManpowerDrainPercent { get; set; }
        public int RaidDailyPoolDrainCapPercent { get; set; }
        public int SiegeDevastateRetainPercent { get; set; }
        public int SiegePillageRetainPercent { get; set; }
        public int SiegeMercyRetainPercent { get; set; }
        public float BattleCasualtyDrainMultiplier { get; set; }
        public int ConquestPoolRetainPercent { get; set; }
        public bool EnableDynamicConquestProtection { get; set; }
        public int ConquestDepletedRetainPercent { get; set; }
        public int ConquestDepletedThresholdPercent { get; set; }
        public bool EnableDelayedRecovery { get; set; }
        public int RaidRecoveryDays { get; set; }
        public int SiegeRecoveryDays { get; set; }
        public int ConquestRecoveryDays { get; set; }
        public int RecoveryPenaltyRaidPercent { get; set; }
        public int RecoveryPenaltySiegePercent { get; set; }
        public int RecoveryPenaltyConquestPercent { get; set; }
        public int RecoveryPenaltyMaxPercent { get; set; }
        public bool ReduceRecoveryPenaltyWhenDepleted { get; set; }
        public int RecoveryDepletedThresholdPercent { get; set; }
        public bool EnableRecruitmentVariance { get; set; }
        public int VolunteerVariancePercent { get; set; }
        public int RecoveryVariancePercent { get; set; }
        public bool EnableSeasonalRegen { get; set; }
        public int SpringSummerRegenMultiplier { get; set; }
        public int WinterRegenMultiplier { get; set; }
        public bool EnablePeaceDividend { get; set; }
        public int PeaceDividendMultiplier { get; set; }
        public bool EnableCultureDiscount { get; set; }
        public int CultureCostPercent { get; set; }
        public bool EnableGovernorBonus { get; set; }
        public float GovernorStewardRegenDivisor { get; set; }
        public float GovernorLeadershipPoolDivisor { get; set; }
        public bool EnableManpowerAlerts { get; set; }
        public int AlertThresholdPercent { get; set; }
        public bool EnableMilitiaLink { get; set; }
        public int MilitiaManpowerMinScale { get; set; }
        public int MilitiaManpowerMaxScale { get; set; }
        public bool EnableWarExhaustion { get; set; }
        public float ExhaustionDailyDecay { get; set; }
        public float ExhaustionRegenDivisor { get; set; }
        public float ExhaustionMaxScore { get; set; }
        public float BattleExhaustionPerCasualty { get; set; }
        public float RaidExhaustionGain { get; set; }
        public float SiegeExhaustionDefender { get; set; }
        public float SiegeExhaustionAttacker { get; set; }
        public float ConquestExhaustionGain { get; set; }
        public bool EnableNobleCaptureExhaustion { get; set; }
        public float NobleCaptureExhaustionGain { get; set; }
        public bool EnableTierWeightedCasualties { get; set; }
        public bool EnableManpowerDepletionAmplifier { get; set; }
        public float ManpowerDepletionAmplifier { get; set; }
        public bool EnableExhaustionDiplomacyPressure { get; set; }
        public float DiplomacyNoNewWarThreshold { get; set; }
        public float DiplomacyPeacePressureThreshold { get; set; }
        public float DiplomacyWarSupportPenaltyPerPoint { get; set; }
        public float DiplomacyPeaceSupportBonusPerPoint { get; set; }
        public bool EnableForcedPeaceAtCrisis { get; set; }
        public float DiplomacyForcedPeaceThreshold { get; set; }
        public int DiplomacyForcedPeaceCooldownDays { get; set; }
        public int DiplomacyForcedPeaceMaxActiveWars { get; set; }
        public int MinWarDurationDaysBeforeForcedPeace { get; set; }
        public float EarlyWarPeacePenaltyStrength { get; set; }
        public bool IgnoreForcedPeaceIfEnemyBesiegingCoreSettlement { get; set; }
        public bool EnableTruceEnforcement { get; set; }
        public int ForcedPeaceTruceDays { get; set; }
        public int DiplomacyMajorWarPressureStartCount { get; set; }
        public float DiplomacyExtraPeaceBiasPerMajorWar { get; set; }
        public float DiplomacyForcedPeaceThresholdReductionPerMajorWar { get; set; }
        public bool EnableMultiFrontWarRelief { get; set; }
        public int EmergencyMinWarDays { get; set; }
        public int EmergencyManpowerThresholdPercent { get; set; }
        public int EmergencyWarCountThreshold { get; set; }
        public bool DiplomacyEnforcePlayerParity { get; set; }
        public bool EnableDiplomacyPressureBands { get; set; }
        public float PressureBandRisingStart { get; set; }
        public float PressureBandCrisisStart { get; set; }
        public float PressureBandHysteresis { get; set; }
        public float PeaceBiasBandLow { get; set; }
        public float PeaceBiasBandHigh { get; set; }
        public float WarSupportPenaltyCap { get; set; }
        public float PeaceSupportBonusCap { get; set; }
        public bool EnableManpowerDiplomacyPressure { get; set; }
        public int ManpowerDiplomacyThresholdPercent { get; set; }
        public float ManpowerDiplomacyPressureStrength { get; set; }
        public bool DiplomacyDebugLogs { get; set; }
        public bool EnableSettlementManpowerTooltips { get; set; }
        public bool EnableSlaveEconomy { get; set; }
        public int SlaveHearthDivisor { get; set; }
        public float SlaveRansomMultiplier { get; set; }
        public float SlaveManpowerPerUnit { get; set; }
        public int SlaveManpowerCapPerTown { get; set; }
        public float SlaveProsperityPerUnit { get; set; }
        public float SlaveConstructionAcceleration { get; set; }
        public float SlaveConstructionBonusCap { get; set; }
        public float SlaveFoodConsumptionPerUnit { get; set; }
        public float SlaveDailyDecayPercent { get; set; }
        public float SlaveCapPerProsperity { get; set; }
        public int SlaveCapMinimum { get; set; }
        public float SlavePriceDecayRate { get; set; }
        public bool EnableSlaveConversionSelection { get; set; }
        public bool EnableEnslavementRogueryXp { get; set; }
        public float EnslavementRogueryXpMultiplier { get; set; }
        public bool EnableDemobilizationSystem { get; set; }
        public int DemobilizationIntensityPreset { get; set; }
        public bool EnableDemobilizationHotkey { get; set; }
        public int DemobilizationHotkeyChoice { get; set; }
        public int DemobilizationWarningLeadDays { get; set; }
        public bool DemobilizationWarningPopup { get; set; }
        public bool DemobilizationNotifyPlayer { get; set; }
        public int DemobilizationExtensionDays { get; set; }
        public int DemobilizationExtensionGoldPerTierDay { get; set; }
        public bool DemobilizationAiExtensionsEnabled { get; set; }
        public int DemobilizationAiExtensionGoldBufferMultiplier { get; set; }
        public int DemobilizationPromotionBonusDays { get; set; }
        public int DemobilizationDailyCapPercent { get; set; }
        public int DemobilizationMaxDailyDepartures { get; set; }
        public bool EnableDemobilizationSeasonality { get; set; }
        public int DemobilizationSpringSummerThresholdPercent { get; set; }
        public int DemobilizationWinterThresholdPercent { get; set; }
        public bool EnableDemobilizationCrisisCompression { get; set; }
        public int DemobilizationCrisisThresholdPercent { get; set; }
        public int DemobilizationMaxExtensions { get; set; }
        public int DemobilizationNotifyIntervalDays { get; set; }
        public bool EnableDemobilizationVeteranReturn { get; set; }
        public int DemobilizationManpowerReturnPercent { get; set; }
        public int DemobilizationVeteranRetentionDays { get; set; }
        public int DemobilizationVeteranSettlingDays { get; set; }
        public int DemobilizationVeteranScatterPercent { get; set; }
        public int DemobilizationRecallGoldPerTier { get; set; }
        public int DemobilizationVeteranRecallAccess { get; set; }
        public bool EnableDemobilizationRemoteRecall { get; set; }
        public bool EnableVeteranRecallHotkey { get; set; }
        public int VeteranRecallHotkeyChoice { get; set; }
        public int DemobilizationCourierSpeed { get; set; }
        public int DemobilizationMarchSpeed { get; set; }
        public bool EnableDemobilizationAiRecall { get; set; }
        public int DemobilizationT1ServiceDays { get; set; }
        public int DemobilizationT2ServiceDays { get; set; }
        public int DemobilizationT3ServiceDays { get; set; }
        public int DemobilizationT4ServiceDays { get; set; }
        public int DemobilizationT5ServiceDays { get; set; }
        public int DemobilizationT6ServiceDays { get; set; }
        public int SlaveConstructionBonusDays { get; set; }
        public bool EnableExperimentalHoverFallback { get; set; }
        public int TooltipRefreshMs { get; set; }
        public bool EnableMinorFactionIncome { get; set; }
        public int MinorFactionMercenaryStipendPerTier { get; set; }
        public int MinorFactionUnalignedStipendPerTier { get; set; }
        public bool EnableGovernanceStrain { get; set; }
        public float GovernanceStrainDecayPerDay { get; set; }
        public float GovernanceMaxLoyaltyPenalty { get; set; }
        public float GovernanceMaxSecurityPenalty { get; set; }
        public float GovernanceMaxProsperityPenalty { get; set; }
        public float GovernanceStrainCap { get; set; }
        public float MaxCombinedModProsperityPenalty { get; set; }
        public bool EnableGovernanceStabilization { get; set; }
        public bool GovernanceStabilizationNotifyPlayer { get; set; }
        public bool GovernanceStabilizationAiEnabled { get; set; }
        public float GovernanceStabilizationAiStrainThreshold { get; set; }
        public int GovernanceStabilizationAiGoldMultiplier { get; set; }
        public int GovernanceStabilizationAiHeroCooldownDays { get; set; }
        public int GovernanceStabilizationCostDonative { get; set; }
        public int GovernanceStabilizationDurationDonative { get; set; }
        public float GovernanceStabilizationStrainDonative { get; set; }
        public float GovernanceStabilizationLoyaltyDonative { get; set; }
        public float GovernanceStabilizationSecurityDonative { get; set; }
        public float GovernanceStabilizationDecayDonative { get; set; }
        public int GovernanceStabilizationCostElites { get; set; }
        public int GovernanceStabilizationDurationElites { get; set; }
        public float GovernanceStabilizationStrainElites { get; set; }
        public float GovernanceStabilizationLoyaltyElites { get; set; }
        public float GovernanceStabilizationSecurityElites { get; set; }
        public float GovernanceStabilizationDecayElites { get; set; }
        public int GovernanceStabilizationCostAmnesty { get; set; }
        public int GovernanceStabilizationDurationAmnesty { get; set; }
        public float GovernanceStabilizationStrainAmnesty { get; set; }
        public float GovernanceStabilizationLoyaltyAmnesty { get; set; }
        public float GovernanceStabilizationSecurityAmnesty { get; set; }
        public float GovernanceStabilizationDecayAmnesty { get; set; }
        public bool EnableFrontierDevastation { get; set; }
        public float DevastationPerRaid { get; set; }
        public float DevastationDecayPerDay { get; set; }
        public float DevastationMaxHearthPenalty { get; set; }
        public float DevastationMaxProsperityPenalty { get; set; }
        public float DevastationMaxSecurityPenalty { get; set; }
        public float DevastationMaxFoodPenaltyPerVillage { get; set; }
        public bool EnableCastleRecruitment { get; set; }
        public int CastlePrisonerAutoEnslaveTierMax { get; set; }
        public int CastleRecruitT4Days { get; set; }
        public int CastleRecruitT5Days { get; set; }
        public int CastleRecruitT6Days { get; set; }
        public int CastleRecruitGoldT2 { get; set; }
        public int CastleRecruitGoldT3 { get; set; }
        public int CastleRecruitGoldT4 { get; set; }
        public int CastleRecruitGoldT5 { get; set; }
        public int CastleRecruitGoldT6 { get; set; }
        public bool CastleRecruitDrainsManpower { get; set; }
        public int CastleElitePoolMax { get; set; }
        public int CastleEliteRegenMin { get; set; }
        public int CastleEliteRegenMax { get; set; }
        public int CastleEliteManpowerCost { get; set; }
        public bool CastleEliteAiRecruits { get; set; }
        public int CastleHoldingFeePercent { get; set; }
        public bool CastleOpenAccess { get; set; }
        public int CastleRecruitmentAccess { get; set; }
        public bool EnableDiversifiedCastlePool { get; set; }
        public int CastlePoolT2LevyPercent { get; set; }
        public int CastlePoolT2NoblePercent { get; set; }
        public int CastlePoolT3T4Percent { get; set; }
        public int CastlePoolT5PlusPercent { get; set; }
        public bool EnableDynamicPoolCapacity { get; set; }
        public int CastleElitePoolBaseCapDynamic { get; set; }
        public float CastleElitePoolProsperityScaling { get; set; }
        public int CastleElitePoolWallBonus { get; set; }
        public int CastleAiGoldBufferMultiplier { get; set; }
        public bool EnableVillageInvestment { get; set; }
        public int VillageInvestCostModest { get; set; }
        public int VillageInvestCostGenerous { get; set; }
        public int VillageInvestCostGrand { get; set; }
        public int VillageInvestDurationModest { get; set; }
        public int VillageInvestDurationGenerous { get; set; }
        public int VillageInvestDurationGrand { get; set; }
        public float VillageInvestHearthModest { get; set; }
        public float VillageInvestHearthGenerous { get; set; }
        public float VillageInvestHearthGrand { get; set; }
        public int VillageInvestRelationModest { get; set; }
        public int VillageInvestRelationGenerous { get; set; }
        public int VillageInvestRelationGrand { get; set; }
        public float VillageInvestInfluenceModest { get; set; }
        public float VillageInvestInfluenceGenerous { get; set; }
        public float VillageInvestInfluenceGrand { get; set; }
        public int VillageInvestPowerModest { get; set; }
        public int VillageInvestPowerGenerous { get; set; }
        public int VillageInvestPowerGrand { get; set; }
        public int VillageInvestPowerCap { get; set; }
        public int VillageInvestCrossClanRelation { get; set; }
        public bool VillageInvestAiEnabled { get; set; }
        public int VillageInvestAiGoldMultiplier { get; set; }
        public int VillageInvestAiChance { get; set; }
        public bool VillageInvestAiRandomTier { get; set; }
        public int VillageInvestAiHeroCooldownDays { get; set; }
        public int VillageInvestAiHearthCeiling { get; set; }
        public bool VillageInvestNotifyPlayer { get; set; }
        public bool EnableTownInvestment { get; set; }
        public int TownInvestCostModest { get; set; }
        public int TownInvestCostGenerous { get; set; }
        public int TownInvestCostGrand { get; set; }
        public int TownInvestDurationModest { get; set; }
        public int TownInvestDurationGenerous { get; set; }
        public int TownInvestDurationGrand { get; set; }
        public float TownInvestProsperityModest { get; set; }
        public float TownInvestProsperityGenerous { get; set; }
        public float TownInvestProsperityGrand { get; set; }
        public int TownInvestRelationModest { get; set; }
        public int TownInvestRelationGenerous { get; set; }
        public int TownInvestRelationGrand { get; set; }
        public float TownInvestInfluenceModest { get; set; }
        public float TownInvestInfluenceGenerous { get; set; }
        public float TownInvestInfluenceGrand { get; set; }
        public int TownInvestPowerModest { get; set; }
        public int TownInvestPowerGenerous { get; set; }
        public int TownInvestPowerGrand { get; set; }
        public int TownInvestPowerCap { get; set; }
        public int TownInvestCrossClanRelation { get; set; }
        public bool TownInvestAiEnabled { get; set; }
        public int TownInvestAiGoldMultiplier { get; set; }
        public int TownInvestAiChance { get; set; }
        public bool TownInvestAiRandomTier { get; set; }
        public int TownInvestAiHeroCooldownDays { get; set; }
        public int TownInvestAiProsperityCeiling { get; set; }
        public bool TownInvestNotifyPlayer { get; set; }
        public bool EnableClanSurvival { get; set; }
        public bool RescueRebelClans { get; set; }
        public bool PurgeLeftoverRebelClans { get; set; }
        public int ClanSurvivalGracePeriodDays { get; set; }
        public float ClanSurvivalCultureWeight { get; set; }
    }
}
